name: Lint
on:
  - push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: phplint, laravel/pint
          coverage: none
      - name: Check syntax
        run: phplint .
      - name: Check code style
        run: pint --test
